pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                // sh '''
                // Hello this is my first Jenkins pipeline
                // '''
            }
        }
    }
}
